// Package webhookauthtest is the VerificationScheme conformance suite
// (Stage 10.3 W1a, WH-VENDOR-SCHEME-1; 01-provider-trust-analysis.md §1.2
// SC1-SC13, as conditioned by 04-review-security.md C3/C9/C10/C11 and the
// binding QA plan 04-review-qa.md §4 W1a). Every scheme - the platform MOCK
// schemes and every future real vendor scheme - must pass
// RunSchemeConformance before it may be registered (see
// webhookauth.ConformanceManifest and this package's registry test).
//
// Rules the suite enforces on itself:
//
//   - It tests the RAW scheme, never the platform wrappers
//     (webhookauth.ExtractInbound/VerifyInbound), so a platform-side defence
//     can never mask a broken scheme.
//   - Tampering is generated by the suite (SC2): every byte of the body and
//     of every header the fixture DECLARES as authentication material is
//     flipped, and each such header is truncated and extended. The fixture
//     only declares the header set.
//   - SC7 (timestamp window) is fail-not-skip for every non-synthetic
//     scheme. The MOCK is exempt only because it is synthetic (its bytes
//     are frozen; replay is inert by idempotency) and can never run in
//     production.
//   - A non-synthetic scheme needs at least one vendor known-answer vector
//     (KAV) taken from the vendor's documentation or a recorded sandbox
//     delivery, with provenance, so a bug shared by the fixture's Sign and
//     the scheme's Verify cannot pass.
//   - Each mandatory case is load-bearing: the package's self-test runs one
//     deliberately broken reference scheme per mandatory case and proves
//     that exactly that case, and no other, goes red.
//
// Constant-time comparison cannot be proven black-box; it is enforced by the
// AST rule in internal/webhookauth (constant_time_lint_test.go).
//
// This is a non-_test package so that domain packages' tests can import it;
// it must never be imported by production code.
package webhookauthtest

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	mathrand "math/rand"
	"net/http"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"

	"github.com/Diansalas/igaming-platform/internal/webhookauth"
)

// Fixture is what a scheme's owner supplies. Sign must implement the
// vendor's DOCUMENTED algorithm (or replay recorded sandbox fixtures) -
// never an invented one.
type Fixture struct {
	// Scheme under test.
	Scheme webhookauth.VerificationScheme
	// AuthHeaders is every request header the scheme treats as
	// authentication material (signature, key id, timestamp, account id,
	// ...). The suite tampers every byte of each. Order matters only for
	// SC13 (cross-domain header mapping).
	AuthHeaders []string
	// KeyIDHeader names the key-id header. Required (and must be one of
	// AuthHeaders) iff Properties().KeySelection == KeyFromHeader.
	KeyIDHeader string
	// Sign returns the authentication headers for body routed as
	// (tenantID, providerID), signed with cred at time at. It uses
	// cred.KeyID (KeyFromHeader) and cred.BoundAccountID
	// (PerMerchantKeySignedAccount) as the vendor would.
	Sign func(cred webhookauth.Credential, tenantID uuid.UUID, providerID string, body []byte, at time.Time) http.Header
	// NewCredential returns a fresh credential with an independent random
	// secret of at least webhookauth.MinSecretBytes for (tenant, provider,
	// key id).
	NewCredential func(tenantID uuid.UUID, providerID, keyID string) webhookauth.Credential
	// Now is the platform clock for the run; zero means DefaultNow.
	Now time.Time
	// KnownAnswers are vendor known-answer vectors. At least one valid
	// vector is required for a non-synthetic scheme.
	KnownAnswers []KnownAnswer
	// CrossDomain (synthetic MOCK schemes only, SC13) are the other
	// domains' MOCK fixtures; their AuthHeaders must be in the same order
	// (signature, key id) as this fixture's.
	CrossDomain []Fixture
}

// KnownAnswer is one vendor known-answer vector. It must contain no real
// credential: a vendor-published test key, or a sandbox key rotated after
// capture.
type KnownAnswer struct {
	// Provenance is where the vector comes from (document + section, or
	// sandbox capture id and date). Required.
	Provenance string
	Credential webhookauth.Credential
	Inbound    webhookauth.Inbound
	Now        time.Time
	WantValid  bool
}

// DefaultNow is the fixed platform clock used when Fixture.Now is zero.
var DefaultNow = time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)

// Case IDs. Mandatory cases are proven load-bearing by the self-test.
const (
	CaseP0   = "P0_FixtureAndPropertiesValid"
	CaseSC1  = "SC1_GenuineSignatureVerifies"
	CaseSC2  = "SC2_SuiteGeneratedTamperingRejected"
	CaseSC3  = "SC3_TenantBinding"
	CaseSC4  = "SC4_ProviderBinding"
	CaseSC5  = "SC5_ExtractMissingMalformedAndFuzz"
	CaseSC6  = "SC6_KeyIDSelectionFromPropertiesOnly"
	CaseSC7  = "SC7_TimestampWindow"
	CaseSC8  = "SC8_SignedAccountBinding"
	CaseSC9  = "SC9_RotationOverlapNotAfter"
	CaseSC10 = "SC10_EmptyOrShortSecretRejected"
	CaseSC11 = "SC11_ClosedErrorContractNoLeak"
	CaseSC12 = "SC12_DuplicateAuthHeadersDeterministic"
	CaseSC13 = "SC13_CrossDomainEqualKeyRejected"
	CaseKAV  = "KAV_KnownAnswerVectors"
)

type caseDef struct {
	id  string
	run func(r *reporter, e *env)
}

func cases() []caseDef {
	return []caseDef{
		{CaseP0, caseP0},
		{CaseSC1, caseSC1},
		{CaseSC2, caseSC2},
		{CaseSC3, caseSC3},
		{CaseSC4, caseSC4},
		{CaseSC5, caseSC5},
		{CaseSC6, caseSC6},
		{CaseSC7, caseSC7},
		{CaseSC8, caseSC8},
		{CaseSC9, caseSC9},
		{CaseSC10, caseSC10},
		{CaseSC11, caseSC11},
		{CaseSC12, caseSC12},
		{CaseSC13, caseSC13},
		{CaseKAV, caseKAV},
	}
}

// CaseIDs returns every case id, in run order.
func CaseIDs() []string {
	cs := cases()
	ids := make([]string, len(cs))
	for i, c := range cs {
		ids[i] = c.id
	}
	return ids
}

// Report maps each case id to its failure messages (empty = passed).
type Report map[string][]string

// Failed returns the sorted ids of the failed cases.
func (r Report) Failed() []string {
	var ids []string
	for id, msgs := range r {
		if len(msgs) > 0 {
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)
	return ids
}

// Evaluate runs every case against f and returns the per-case failures,
// without a *testing.T (used by the self-test). A panic inside a case is
// that case's failure.
func Evaluate(f Fixture) Report {
	rep := Report{}
	for _, c := range cases() {
		rep[c.id] = runCase(c, f)
	}
	return rep
}

// RunSchemeConformance runs every case as a subtest of t.
func RunSchemeConformance(t *testing.T, f Fixture) {
	t.Helper()
	for _, c := range cases() {
		t.Run(c.id, func(t *testing.T) {
			for _, msg := range runCase(c, f) {
				t.Error(msg)
			}
		})
	}
}

// MissingConformance returns, sorted, every manifest scheme name that has
// no conformance fixture. The registry-driven test fails on any.
func MissingConformance(manifest []string, fixtures map[string]func() Fixture) []string {
	var missing []string
	for _, name := range manifest {
		if mk, ok := fixtures[name]; !ok || mk == nil {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)
	return missing
}

type reporter struct{ failures []string }

func (r *reporter) errorf(format string, args ...any) {
	r.failures = append(r.failures, fmt.Sprintf(format, args...))
}

func runCase(c caseDef, f Fixture) (failures []string) {
	r := &reporter{}
	defer func() {
		if p := recover(); p != nil {
			r.errorf("%s: panicked: %v", c.id, p)
		}
		failures = r.failures
	}()
	c.run(r, newEnv(f))
	return r.failures
}

// env is one case's fresh world: two tenants, two providers, fresh keys.
type env struct {
	f       Fixture
	p       webhookauth.SchemeProperties
	now     time.Time
	tenantA uuid.UUID
	tenantB uuid.UUID
	provA   string
	provB   string
	body    []byte
}

func newEnv(f Fixture) *env {
	now := f.Now
	if now.IsZero() {
		now = DefaultNow
	}
	var p webhookauth.SchemeProperties
	if f.Scheme != nil {
		p = f.Scheme.Properties()
	}
	return &env{
		f: f, p: p, now: now,
		tenantA: uuid.New(), tenantB: uuid.New(),
		provA: "conformance-provider-a", provB: "conformance-provider-b",
		body: []byte(`{"conformance":"body","amount":1000,"ref":"sc-0001"}`),
	}
}

// cred returns a fresh credential; for a signed-account scheme it is bound
// to a per-(tenant, provider) merchant account id, as a real handle would be.
func (e *env) cred(tenantID uuid.UUID, providerID, keyID string) webhookauth.Credential {
	c := e.f.NewCredential(tenantID, providerID, keyID)
	if e.p.Binding == webhookauth.BindingPerMerchantKeySignedAccount && c.BoundAccountID == "" {
		c.BoundAccountID = "conformance-acct-" + tenantID.String()[:8] + "-" + providerID[len(providerID)-1:]
	}
	return c
}

func (e *env) signed(cred webhookauth.Credential, tenantID uuid.UUID, providerID string, body []byte, at time.Time) webhookauth.Inbound {
	h := e.f.Sign(cred, tenantID, providerID, body, at)
	return webhookauth.Inbound{TenantID: tenantID, ProviderID: providerID, Header: h, Body: append([]byte(nil), body...)}
}

// outcome is one Extract+Verify run against the raw scheme.
type outcome struct {
	extractOK bool
	reason    webhookauth.Reason
	matched   string
	err       error
	panicked  any
}

func (o outcome) accepted() bool { return o.panicked == nil && o.extractOK && o.err == nil }

// sigRejected: rejected as a signature failure (Extract failure, or
// errors.Is ErrSignatureInvalid but NOT a timestamp-window failure - C10:
// timestamp_out_of_window only when the MAC is otherwise valid).
func (o outcome) sigRejected() bool {
	if o.panicked != nil {
		return false
	}
	if !o.extractOK {
		return true
	}
	return errors.Is(o.err, webhookauth.ErrSignatureInvalid) && !errors.Is(o.err, webhookauth.ErrTimestampOutOfWindow)
}

func (o outcome) String() string {
	if o.panicked != nil {
		return fmt.Sprintf("panic(%v)", o.panicked)
	}
	if !o.extractOK {
		return fmt.Sprintf("extract-rejected(%s)", o.reason)
	}
	if o.err != nil {
		return fmt.Sprintf("verify-rejected(%q)", o.err.Error())
	}
	return fmt.Sprintf("ACCEPTED(matched=%q)", o.matched)
}

func (e *env) run(creds webhookauth.CredentialSet, in webhookauth.Inbound, now time.Time) (o outcome) {
	defer func() {
		if p := recover(); p != nil {
			o = outcome{panicked: p}
		}
	}()
	m, reason, ok := e.f.Scheme.Extract(in)
	if !ok {
		return outcome{reason: reason}
	}
	matched, err := e.f.Scheme.Verify(creds, in, m, now)
	return outcome{extractOK: true, matched: matched, err: err}
}

func one(c webhookauth.Credential) webhookauth.CredentialSet {
	return webhookauth.CredentialSet{Active: c}
}

func cloneInbound(in webhookauth.Inbound) webhookauth.Inbound {
	out := in
	out.Header = in.Header.Clone()
	if out.Header == nil {
		out.Header = http.Header{}
	}
	out.Body = append([]byte(nil), in.Body...)
	return out
}

func (e *env) keyFromHeader() bool { return e.p.KeySelection == webhookauth.KeyFromHeader }

// ---------------------------------------------------------------------------
// P0 - the fixture is usable and the declaration is PERMITTED.

func caseP0(r *reporter, e *env) {
	if e.f.Scheme == nil || e.f.Sign == nil || e.f.NewCredential == nil {
		r.errorf("fixture must supply Scheme, Sign and NewCredential")
		return
	}
	if err := webhookauth.ValidateProperties(e.p); err != nil {
		r.errorf("Properties() is not a permitted declaration: %v", err)
	}
	if len(e.f.AuthHeaders) == 0 {
		r.errorf("fixture must declare its authentication headers (the suite tampers them)")
	}
	if e.keyFromHeader() {
		found := false
		for _, h := range e.f.AuthHeaders {
			found = found || http.CanonicalHeaderKey(h) == http.CanonicalHeaderKey(e.f.KeyIDHeader)
		}
		if e.f.KeyIDHeader == "" || !found {
			r.errorf("a KeyFromHeader scheme's fixture must name KeyIDHeader and include it in AuthHeaders")
		}
	}
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	if len(c.Secret) < webhookauth.MinSecretBytes {
		r.errorf("NewCredential must return a secret of at least %d bytes", webhookauth.MinSecretBytes)
	}
	in := e.signed(c, e.tenantA, e.provA, e.body, e.now)
	for _, h := range e.f.AuthHeaders {
		if in.Header.Get(h) == "" {
			r.errorf("declared auth header %q is absent from a signed request", h)
		}
	}
}

// ---------------------------------------------------------------------------
// SC1 - a genuine signature verifies (also: empty body; determinism; Extract
// is pure and needs no tenant id, as the HTTP preamble calls it pre-tenant).

func caseSC1(r *reporter, e *env) {
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	for _, body := range [][]byte{e.body, {}} {
		in := e.signed(c, e.tenantA, e.provA, body, e.now)
		o := e.run(one(c), in, e.now)
		if !o.accepted() {
			r.errorf("genuine request (body len %d) not accepted: %s", len(body), o)
			continue
		}
		if o.matched != c.KeyID {
			r.errorf("Verify must return the matched credential's key id %q, got %q", c.KeyID, o.matched)
		}
		if again := e.run(one(c), in, e.now); !again.accepted() {
			r.errorf("verification is not deterministic: second run %s", again)
		}
		pre := cloneInbound(in)
		pre.TenantID = uuid.Nil
		m, reason, ok := e.f.Scheme.Extract(pre)
		if !ok {
			r.errorf("Extract of a genuine request must succeed without a tenant id (pure, pre-tenant): %s", reason)
		}
		if e.keyFromHeader() && m.KeyID != c.KeyID {
			r.errorf("KeyFromHeader Extract must return the header key id %q, got %q", c.KeyID, m.KeyID)
		}
		if !e.keyFromHeader() && m.KeyID != "" {
			r.errorf("KeyImplicit Extract must return an empty key id, got %q", m.KeyID)
		}
	}
}

// ---------------------------------------------------------------------------
// SC2 - suite-generated tampering: every byte of the body and of every
// declared auth header is flipped; each auth header is also truncated and
// extended. Each must be rejected as a SIGNATURE failure (never a
// timestamp-window failure, C10).

func caseSC2(r *reporter, e *env) {
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	genuine := e.signed(c, e.tenantA, e.provA, e.body, e.now)
	if o := e.run(one(c), genuine, e.now); !o.accepted() {
		r.errorf("precondition: genuine request not accepted: %s", o)
		return
	}
	for i := range genuine.Body {
		in := cloneInbound(genuine)
		in.Body[i] ^= 0x01
		if o := e.run(one(c), in, e.now); !o.sigRejected() {
			r.errorf("body byte %d flipped: want signature rejection, got %s", i, o)
			return
		}
	}
	for _, h := range e.f.AuthHeaders {
		v := genuine.Header.Get(h)
		isKeyID := e.keyFromHeader() && http.CanonicalHeaderKey(h) == http.CanonicalHeaderKey(e.f.KeyIDHeader)
		var variants []string
		for i := 0; i < len(v); i++ {
			b := []byte(v)
			b[i] ^= 0x01
			variants = append(variants, string(b))
		}
		variants = append(variants, v+"0", v+"f", v[:len(v)/2])
		if len(v) > 0 {
			variants = append(variants, v[:len(v)-1])
		}
		if !isKeyID {
			// An ABSENT key id is SC6's concern (C3); every other auth
			// header must also reject deletion.
			variants = append(variants, "")
		}
		for _, nv := range variants {
			if nv == v || (isKeyID && nv == "") {
				continue
			}
			in := cloneInbound(genuine)
			if nv == "" {
				in.Header.Del(h)
			} else {
				in.Header.Set(h, nv)
			}
			if o := e.run(one(c), in, e.now); !o.sigRejected() {
				r.errorf("auth header %s tampered to %q: want signature rejection, got %s", h, nv, o)
				return
			}
		}
	}
}

// ---------------------------------------------------------------------------
// SC3 - tenant binding.

func caseSC3(r *reporter, e *env) {
	cA := e.cred(e.tenantA, e.provA, "conf-key-a")
	cB := e.cred(e.tenantB, e.provA, "conf-key-a")
	inA := e.signed(cA, e.tenantA, e.provA, e.body, e.now)

	atB := cloneInbound(inA)
	atB.TenantID = e.tenantB
	if o := e.run(one(cB), atB, e.now); o.accepted() {
		r.errorf("A-signed request at tenant B's route verified with B's credential: %s", o)
	}
	if o := e.run(one(cA), atB, e.now); o.accepted() {
		r.errorf("A's credential verified a request routed as tenant B: %s", o)
	}
	if e.p.Binding == webhookauth.BindingSignedTenant {
		relabeled := cA
		relabeled.TenantID = e.tenantB
		if o := e.run(one(relabeled), atB, e.now); o.accepted() {
			r.errorf("SignedTenant: an EQUAL key relabeled to tenant B verified A-signed bytes at B's route (tenant not in the MAC): %s", o)
		}
	}
}

// ---------------------------------------------------------------------------
// SC4 - provider binding (the same checks across two provider ids).

func caseSC4(r *reporter, e *env) {
	cA := e.cred(e.tenantA, e.provA, "conf-key-a")
	cB := e.cred(e.tenantA, e.provB, "conf-key-a")
	inA := e.signed(cA, e.tenantA, e.provA, e.body, e.now)

	atB := cloneInbound(inA)
	atB.ProviderID = e.provB
	if o := e.run(one(cB), atB, e.now); o.accepted() {
		r.errorf("provider-A-signed request at provider B's route verified with B's credential: %s", o)
	}
	if o := e.run(one(cA), atB, e.now); o.accepted() {
		r.errorf("provider A's credential verified a request routed as provider B: %s", o)
	}
	if e.p.Binding == webhookauth.BindingSignedTenant {
		relabeled := cA
		relabeled.ProviderID = e.provB
		if o := e.run(one(relabeled), atB, e.now); o.accepted() {
			r.errorf("SignedTenant: an EQUAL key relabeled to provider B verified provider-A bytes (provider not in the MAC): %s", o)
		}
	}
}

// ---------------------------------------------------------------------------
// SC5 - Extract: missing -> signature_missing, malformed -> signature_invalid,
// fuzzed for panics; nothing malformed ever verifies.

var malformedValues = []string{"\x00", "%%%", " ", "not a signature", "\xff\xfe\xfd", strings.Repeat("A", 4096), "v2=zz", "=="}

func caseSC5(r *reporter, e *env) {
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	genuine := e.signed(c, e.tenantA, e.provA, e.body, e.now)

	extract := func(in webhookauth.Inbound) (reason webhookauth.Reason, ok bool, panicked any) {
		defer func() { panicked = recover() }()
		_, reason, ok = e.f.Scheme.Extract(in)
		return reason, ok, nil
	}
	check := func(label string, in webhookauth.Inbound, want webhookauth.Reason) {
		reason, ok, p := extract(in)
		switch {
		case p != nil:
			r.errorf("%s: Extract panicked: %v", label, p)
		case ok:
			if o := e.run(one(c), in, e.now); o.accepted() {
				r.errorf("%s: Extract accepted and the request VERIFIED", label)
			}
		case want != "" && reason != want:
			r.errorf("%s: want reason %s, got %s", label, want, reason)
		case reason != webhookauth.ReasonSignatureMissing && reason != webhookauth.ReasonSignatureInvalid:
			r.errorf("%s: Extract returned a reason outside {signature_missing, signature_invalid}: %s", label, reason)
		}
	}

	none := cloneInbound(genuine)
	none.Header = http.Header{}
	if reason, ok, p := extract(none); p != nil || ok || reason != webhookauth.ReasonSignatureMissing {
		r.errorf("no auth headers: want signature_missing, got ok=%v reason=%s panic=%v", ok, reason, p)
	}
	nilHeader := cloneInbound(genuine)
	nilHeader.Header = nil
	if reason, ok, p := extract(nilHeader); p != nil || ok || reason != webhookauth.ReasonSignatureMissing {
		r.errorf("nil header map: want signature_missing, got ok=%v reason=%s panic=%v", ok, reason, p)
	}
	for _, h := range e.f.AuthHeaders {
		if e.keyFromHeader() && http.CanonicalHeaderKey(h) == http.CanonicalHeaderKey(e.f.KeyIDHeader) {
			continue // an absent key id is SC6's concern (C3)
		}
		in := cloneInbound(genuine)
		in.Header.Del(h)
		if reason, ok, p := extract(in); p != nil || ok || reason != webhookauth.ReasonSignatureMissing {
			r.errorf("header %s missing: want signature_missing, got ok=%v reason=%s panic=%v", h, ok, reason, p)
		}
		for _, bad := range malformedValues {
			in := cloneInbound(genuine)
			in.Header.Set(h, bad)
			check(fmt.Sprintf("header %s malformed (%d bytes)", h, len(bad)), in, webhookauth.ReasonSignatureInvalid)
		}
	}
	// Deterministic fuzz: random header values (16..256 random bytes) in
	// random subsets of the auth headers.
	rng := mathrand.New(mathrand.NewSource(0x5c5))
	for i := 0; i < 400; i++ {
		in := cloneInbound(genuine)
		// Replace a random NON-EMPTY subset of the auth headers.
		forced := rng.Intn(len(e.f.AuthHeaders))
		for j, h := range e.f.AuthHeaders {
			if j != forced && rng.Intn(2) == 0 {
				continue
			}
			b := make([]byte, 16+rng.Intn(241))
			_, _ = rng.Read(b)
			in.Header.Set(h, string(b))
		}
		check(fmt.Sprintf("fuzz #%d", i), in, "")
	}
}

// ---------------------------------------------------------------------------
// SC6 - key-id selection (C3): a key-id mismatch is rejected, and for a
// KeyFromHeader scheme an ABSENT key id is signature_missing - never a
// multi-key trial, even when a Previous credential is on offer.

func caseSC6(r *reporter, e *env) {
	if !e.keyFromHeader() {
		return // KeyImplicit schemes carry no key id; SC1 checks Extract returns "".
	}
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	in := e.signed(c, e.tenantA, e.provA, e.body, e.now)
	other := c
	other.KeyID = "conf-key-other"
	if o := e.run(one(other), in, e.now); o.accepted() {
		r.errorf("header key id %q verified against a credential with key id %q: %s", c.KeyID, other.KeyID, o)
	}

	old := e.cred(e.tenantA, e.provA, "conf-key-old")
	old.NotAfter = e.now.Add(time.Hour)
	active := e.cred(e.tenantA, e.provA, "conf-key-new")
	signedOld := e.signed(old, e.tenantA, e.provA, e.body, e.now)
	signedOld.Header.Del(e.f.KeyIDHeader)
	m, reason, ok := e.f.Scheme.Extract(signedOld)
	if ok || reason != webhookauth.ReasonSignatureMissing {
		r.errorf("KeyFromHeader: an absent key-id header must be signature_missing (C3), got ok=%v reason=%s keyID=%q", ok, reason, m.KeyID)
	}
	set := webhookauth.CredentialSet{Active: active, Previous: &old}
	if ok {
		if _, err := e.f.Scheme.Verify(set, signedOld, m, e.now); err == nil {
			r.errorf("KeyFromHeader: a request WITHOUT a key id verified by trying more than one credential (C3 multi-key trial)")
		}
	}
}

// ---------------------------------------------------------------------------
// SC7 - replay window. Mandatory, fail-not-skip, for every non-synthetic
// scheme.

func caseSC7(r *reporter, e *env) {
	if !e.p.SignedTimestamp {
		if !e.p.Synthetic {
			r.errorf("a non-synthetic scheme must sign a timestamp: SC7 is mandatory (ADR 0022 §3 point 10)")
		}
		return // MOCK exemption (synthetic; bytes frozen; replay inert by idempotency)
	}
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	skew := e.p.MaxSkew
	for _, tc := range []struct {
		label string
		at    time.Time
		valid bool
	}{
		{"stale (now - MaxSkew - 1s)", e.now.Add(-skew - time.Second), false},
		{"future (now + MaxSkew + 1s)", e.now.Add(skew + time.Second), false},
		{"inside (now - MaxSkew + 1s)", e.now.Add(-skew + time.Second), true},
		{"inside (now + MaxSkew - 1s)", e.now.Add(skew - time.Second), true},
		{"very stale (now - 24h)", e.now.Add(-24 * time.Hour), false},
	} {
		in := e.signed(c, e.tenantA, e.provA, e.body, tc.at)
		o := e.run(one(c), in, e.now)
		if tc.valid && !o.accepted() {
			r.errorf("%s: want accepted, got %s", tc.label, o)
		}
		if !tc.valid && (o.panicked != nil || !o.extractOK || !errors.Is(o.err, webhookauth.ErrTimestampOutOfWindow)) {
			r.errorf("%s: want ErrTimestampOutOfWindow (MAC valid, window violated), got %s", tc.label, o)
		}
	}
	stale := e.signed(c, e.tenantA, e.provA, e.body, e.now.Add(-skew-time.Minute))
	stale.Body = append([]byte(nil), stale.Body...)
	stale.Body[0] ^= 0x01
	if o := e.run(one(c), stale, e.now); !o.sigRejected() {
		r.errorf("stale AND tampered: want signature_invalid (timestamp_out_of_window only when the MAC is otherwise valid, C10), got %s", o)
	}
}

// ---------------------------------------------------------------------------
// SC8 - signed account id must equal cred.BoundAccountID.

func caseSC8(r *reporter, e *env) {
	if e.p.Binding != webhookauth.BindingPerMerchantKeySignedAccount {
		return
	}
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	c.BoundAccountID = "merchant-acct-a"
	in := e.signed(c, e.tenantA, e.provA, e.body, e.now)
	if o := e.run(one(c), in, e.now); !o.accepted() {
		r.errorf("precondition: genuine account-bound request not accepted: %s", o)
		return
	}
	for _, acct := range []string{"merchant-acct-b", ""} {
		other := c
		other.BoundAccountID = acct
		if o := e.run(one(other), in, e.now); o.accepted() {
			r.errorf("request signed for account %q verified against a credential bound to %q: %s", c.BoundAccountID, acct, o)
		}
	}
}

// ---------------------------------------------------------------------------
// SC9 - rotation overlap: Previous honoured only before not_after, and only
// for KeyImplicit; a KeyFromHeader scheme never honours Previous.

func caseSC9(r *reporter, e *env) {
	old := e.cred(e.tenantA, e.provA, "conf-key-old")
	active := e.cred(e.tenantA, e.provA, "conf-key-new")
	signedOld := e.signed(old, e.tenantA, e.provA, e.body, e.now)
	if e.keyFromHeader() {
		prev := old
		prev.NotAfter = e.now.Add(time.Hour)
		set := webhookauth.CredentialSet{Active: active, Previous: &prev}
		if o := e.run(set, signedOld, e.now); o.accepted() {
			r.errorf("KeyFromHeader: a Previous credential was honoured (C4: never for KeyFromHeader): %s", o)
		}
		return
	}
	for _, tc := range []struct {
		label    string
		notAfter time.Time
		valid    bool
	}{
		{"before not_after", e.now.Add(time.Hour), true},
		{"after not_after", e.now.Add(-time.Second), false},
		{"at not_after", e.now, false},
		{"zero not_after", time.Time{}, false},
	} {
		prev := old
		prev.NotAfter = tc.notAfter
		set := webhookauth.CredentialSet{Active: active, Previous: &prev}
		o := e.run(set, signedOld, e.now)
		if tc.valid && (!o.accepted() || o.matched != old.KeyID) {
			r.errorf("Previous %s: want accepted with matched key %q, got %s", tc.label, old.KeyID, o)
		}
		if !tc.valid && o.accepted() {
			r.errorf("Previous %s: want rejected, got %s", tc.label, o)
		}
	}
	prev := old
	prev.NotAfter = e.now.Add(time.Hour)
	signedNew := e.signed(active, e.tenantA, e.provA, e.body, e.now)
	if o := e.run(webhookauth.CredentialSet{Active: active, Previous: &prev}, signedNew, e.now); !o.accepted() || o.matched != active.KeyID {
		r.errorf("active key during overlap: want accepted with matched key %q, got %s", active.KeyID, o)
	}
}

// ---------------------------------------------------------------------------
// SC10 - an empty/short secret or an empty CredentialSet is rejected, never
// panics.

func caseSC10(r *reporter, e *env) {
	base := e.cred(e.tenantA, e.provA, "conf-key-a")
	for _, n := range []int{0, 1, webhookauth.MinSecretBytes - 1} {
		c := base
		c.Secret = make([]byte, n)
		_, _ = rand.Read(c.Secret)
		c.Fingerprint = webhookauth.Fingerprint(c.Secret)
		in := e.signed(c, e.tenantA, e.provA, e.body, e.now)
		if o := e.run(one(c), in, e.now); o.accepted() || o.panicked != nil {
			r.errorf("a %d-byte secret must be rejected without panicking, got %s", n, o)
		}
	}
	in := e.signed(base, e.tenantA, e.provA, e.body, e.now)
	if o := e.run(webhookauth.CredentialSet{}, in, e.now); o.accepted() || o.panicked != nil {
		r.errorf("an empty CredentialSet must be rejected without panicking, got %s", o)
	}
	noSecret := base
	noSecret.Secret = nil
	if o := e.run(one(noSecret), in, e.now); o.accepted() || o.panicked != nil {
		r.errorf("a nil secret must be rejected without panicking, got %s", o)
	}
}

// ---------------------------------------------------------------------------
// SC11 - the error value is EXACTLY ErrSignatureInvalid or
// ErrTimestampOutOfWindow (C10), and its text carries no body bytes, secret,
// fingerprint or signature material.

func caseSC11(r *reporter, e *env) {
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	marker := []byte(`{"sc11":"body-marker-7f3a9c","amount":1}`)
	genuine := e.signed(c, e.tenantA, e.provA, marker, e.now)

	var failing []webhookauth.Inbound
	tampered := cloneInbound(genuine)
	tampered.Body[0] ^= 0x01
	failing = append(failing, tampered)
	wrongTenant := cloneInbound(genuine)
	wrongTenant.TenantID = e.tenantB
	failing = append(failing, wrongTenant)
	if e.p.SignedTimestamp {
		failing = append(failing, e.signed(c, e.tenantA, e.provA, marker, e.now.Add(-e.p.MaxSkew-time.Minute)))
	}
	forbidden := []string{string(marker), "body-marker-7f3a9c", hex.EncodeToString(c.Secret), c.Fingerprint}
	for _, h := range e.f.AuthHeaders {
		isKeyID := e.keyFromHeader() && http.CanonicalHeaderKey(h) == http.CanonicalHeaderKey(e.f.KeyIDHeader)
		if v := genuine.Header.Get(h); len(v) >= 8 && !isKeyID {
			forbidden = append(forbidden, v)
		}
	}
	for i, in := range failing {
		o := e.run(one(c), in, e.now)
		if o.panicked != nil || !o.extractOK {
			continue // not a Verify error (SC2/SC5 cover these)
		}
		if o.err == nil {
			continue // acceptance of a bad input is SC2/SC3/SC7's finding, not SC11's
		}
		// Identity, not errors.Is: the contract is the unwrapped sentinel.
		if o.err != webhookauth.ErrSignatureInvalid && o.err != webhookauth.ErrTimestampOutOfWindow {
			r.errorf("failing input #%d: Verify must return exactly ErrSignatureInvalid or ErrTimestampOutOfWindow (unwrapped), got %T %q", i, o.err, o.err.Error())
		}
		text := o.err.Error()
		if bytes.Contains([]byte(text), c.Secret) {
			r.errorf("failing input #%d: error text contains the raw secret", i)
		}
		for _, f := range forbidden {
			if f != "" && strings.Contains(text, f) {
				r.errorf("failing input #%d: error text leaks %q", i, f)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// SC12 - duplicate auth headers behave deterministically (F-6/K13) and a
// request none of whose values verify is rejected.

func caseSC12(r *reporter, e *env) {
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	genuine := e.signed(c, e.tenantA, e.provA, e.body, e.now)
	for _, h := range e.f.AuthHeaders {
		v := genuine.Header.Get(h)
		for _, vals := range [][]string{{v, "x-dup"}, {"x-dup", v}, {"x-dup", "y-dup"}} {
			in := cloneInbound(genuine)
			in.Header.Del(h)
			for _, val := range vals {
				in.Header.Add(h, val)
			}
			first := e.run(one(c), in, e.now)
			second := e.run(one(c), cloneInbound(in), e.now)
			if first.String() != second.String() {
				r.errorf("duplicate %s %q: non-deterministic (%s vs %s)", h, vals, first, second)
			}
			if first.panicked != nil {
				r.errorf("duplicate %s %q: panicked: %v", h, vals, first.panicked)
			}
			if vals[0] != v && vals[1] != v && first.accepted() {
				r.errorf("duplicate %s with no genuine value verified: %s", h, first)
			}
		}
	}
}

// ---------------------------------------------------------------------------
// SC13 - MOCK schemes only: cross-domain separation (ADR 0022 §3 point 8).
// A signature from another domain's MOCK scheme under an EQUAL key, carried
// in this domain's own header names, never verifies.

func caseSC13(r *reporter, e *env) {
	if !e.p.Synthetic {
		return
	}
	if len(e.f.CrossDomain) == 0 {
		r.errorf("a synthetic MOCK fixture must supply its CrossDomain fixtures")
		return
	}
	c := e.cred(e.tenantA, e.provA, "conf-key-a")
	for _, g := range e.f.CrossDomain {
		if g.Sign == nil || len(g.AuthHeaders) != len(e.f.AuthHeaders) {
			r.errorf("cross-domain fixture %T must declare the same number of auth headers", g.Scheme)
			continue
		}
		foreign := g.Sign(c, e.tenantA, e.provA, e.body, e.now)
		in := webhookauth.Inbound{TenantID: e.tenantA, ProviderID: e.provA, Header: http.Header{}, Body: append([]byte(nil), e.body...)}
		for i, h := range e.f.AuthHeaders {
			in.Header.Set(h, foreign.Get(g.AuthHeaders[i]))
		}
		if o := e.run(one(c), in, e.now); o.accepted() {
			r.errorf("a %s signature under an EQUAL key verified in this domain: %s", g.Scheme.Name(), o)
		}
		raw := webhookauth.Inbound{TenantID: e.tenantA, ProviderID: e.provA, Header: foreign, Body: append([]byte(nil), e.body...)}
		if o := e.run(one(c), raw, e.now); o.accepted() {
			r.errorf("a %s request with its own header names verified in this domain: %s", g.Scheme.Name(), o)
		}
	}
}

// ---------------------------------------------------------------------------
// KAV - vendor known-answer vectors (C9 point 1). Required for every
// non-synthetic scheme, so Sign and Verify cannot share a bug.

func caseKAV(r *reporter, e *env) {
	if len(e.f.KnownAnswers) == 0 {
		if !e.p.Synthetic {
			r.errorf("a non-synthetic scheme must supply at least one vendor known-answer vector with provenance")
		}
		return
	}
	anyValid := false
	for i, kav := range e.f.KnownAnswers {
		if strings.TrimSpace(kav.Provenance) == "" {
			r.errorf("known-answer vector #%d has no provenance", i)
		}
		now := kav.Now
		if now.IsZero() {
			now = e.now
		}
		o := e.run(one(kav.Credential), cloneInbound(kav.Inbound), now)
		if kav.WantValid {
			anyValid = true
			if !o.accepted() {
				r.errorf("known-answer vector #%d (%s): want accepted, got %s", i, kav.Provenance, o)
			}
		} else if o.accepted() {
			r.errorf("known-answer vector #%d (%s): want rejected, got %s", i, kav.Provenance, o)
		}
	}
	if !anyValid {
		r.errorf("at least one known-answer vector must be a VALID vendor vector")
	}
}
