# Every secret this deployment needs is generated BY TERRAFORM ITSELF via
# `random_password` — never typed into a tfvars file, never committed
# anywhere. This module produces exactly the three secrets named in the
# Stage 9.3 deployment brief:
#   1. DB master credentials (the "igaming" / migration-owner role — see
#      docs/security/runtime-role-separation.md; on RDS the master user IS
#      this role, not a separate bootstrap identity, since it already owns
#      the initial database/schema and holds CREATEROLE via rds_superuser).
#   2. The igaming_runtime app credential (non-owning runtime role).
#   3. JWT_SIGNING_SECRET.
#
# Passwords are restricted to an alphanumeric charset (special = false) so
# they can be embedded directly into a postgres:// connection string
# elsewhere in this stack without needing URL-encoding logic in Terraform
# or in the container's entrypoint.

resource "random_password" "db_master" {
  length  = 32
  special = false
}

resource "random_password" "db_runtime" {
  length  = 32
  special = false
}

resource "random_password" "jwt_signing" {
  # internal/config requires JWT_SIGNING_SECRET to be at least 32
  # characters; 64 alphanumeric characters is comfortably above that.
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "db_master" {
  name        = "${var.name_prefix}/db-master"
  description = "RDS master (migration-owner, 'igaming') credentials. Generated by Terraform. Used only by cmd/migrate and the one-off role-init task — never by the running application."

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-master-secret" })
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({
    username = var.db_master_username
    password = random_password.db_master.result
  })
}

resource "aws_secretsmanager_secret" "db_runtime" {
  name        = "${var.name_prefix}/db-runtime"
  description = "Non-owning igaming_runtime application credential (PLAT-ROLESPLIT-1). Generated by Terraform. This is what platform-api's DATABASE_URL resolves to."

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-runtime-secret" })
}

resource "aws_secretsmanager_secret_version" "db_runtime" {
  secret_id = aws_secretsmanager_secret.db_runtime.id
  secret_string = jsonencode({
    username = var.db_runtime_username
    password = random_password.db_runtime.result
  })
}

resource "aws_secretsmanager_secret" "jwt_signing" {
  name        = "${var.name_prefix}/jwt-signing-secret"
  description = "JWT_SIGNING_SECRET for platform-api. Generated by Terraform, per-environment, never reused between dev/staging/production."

  tags = merge(var.tags, { Name = "${var.name_prefix}-jwt-signing-secret" })
}

resource "aws_secretsmanager_secret_version" "jwt_signing" {
  secret_id     = aws_secretsmanager_secret.jwt_signing.id
  secret_string = random_password.jwt_signing.result
}
