# Application secrets generated for this deployment, stored in Secrets
# Manager. Two secrets:
#   1. The igaming_runtime app credential (non-owning runtime role, JSON
#      {"username","password"} — docs/security/runtime-role-separation.md).
#   2. JWT_SIGNING_SECRET.
#
# The RDS master ("igaming", migration-owner) credential is NOT generated
# here any more: RDS generates and stores it itself
# (manage_master_user_password — see modules/database), so Terraform never
# handles that value at all.
#
# KEEPING VALUES OUT OF TERRAFORM STATE (ADR 0086). Marking a value
# `sensitive` only redacts it from CLI output — it is still written to state
# in plaintext. Instead, each value here is generated by an EPHEMERAL
# resource (never persisted to state or plan files, Terraform >= 1.10) and
# written through the provider's WRITE-ONLY argument `secret_string_wo`
# (never persisted, Terraform >= 1.11). The state records only the secret
# ARNs/names and `secret_string_wo_version`.
#
# Because an ephemeral value is re-generated on every plan, the provider
# only writes it when `secret_string_wo_version` changes. That makes the
# version number the rotation control: bumping var.secret_version writes a
# brand-new value. After rotating, the runtime password must be propagated
# into Postgres by re-running the role-init task, and services must be
# redeployed to pick up both new values (see the staging runbook).
#
# Passwords use an alphanumeric charset (special = false) so they are safe
# in any connection-string or shell context; containers receive them via
# PGPASSWORD / environment injection, never inside a URL.

ephemeral "random_password" "db_runtime" {
  length  = 32
  special = false
}

ephemeral "random_password" "jwt_signing" {
  # internal/config requires JWT_SIGNING_SECRET to be at least 32
  # characters; 64 alphanumeric characters is comfortably above that.
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "db_runtime" {
  name                    = "${var.name_prefix}/db-runtime"
  description             = "Non-owning igaming_runtime application credential (PLAT-ROLESPLIT-1). Generated ephemerally by Terraform and written write-only (never in Terraform state). platform-api receives its password as PGPASSWORD."
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, { Name = "${var.name_prefix}-db-runtime-secret" })
}

resource "aws_secretsmanager_secret_version" "db_runtime" {
  secret_id = aws_secretsmanager_secret.db_runtime.id
  secret_string_wo = jsonencode({
    username = var.db_runtime_username
    password = ephemeral.random_password.db_runtime.result
  })
  secret_string_wo_version = var.secret_version
}

resource "aws_secretsmanager_secret" "jwt_signing" {
  name                    = "${var.name_prefix}/jwt-signing-secret"
  description             = "JWT_SIGNING_SECRET for platform-api. Generated ephemerally by Terraform and written write-only (never in Terraform state); per-environment, never reused between dev/staging/production."
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, { Name = "${var.name_prefix}-jwt-signing-secret" })
}

resource "aws_secretsmanager_secret_version" "jwt_signing" {
  secret_id                = aws_secretsmanager_secret.jwt_signing.id
  secret_string_wo         = ephemeral.random_password.jwt_signing.result
  secret_string_wo_version = var.secret_version
}
