import { apiFetch, buildQuery } from './client'
import type { PagedResponse } from './types'

// Mirrors internal/httpserver/sportsbook_handlers.go's response shapes
// exactly. Odds are an integer numerator/denominator fraction server-side
// (never a float) - this app only ever converts to a display-only decimal
// string via lib/odds.ts, and never feeds that decimal back into a
// request or a stored value the server relies on.

export interface EventSummary {
  id: string
  name: string
  start_time: string
  status: string
}

export interface CompetitionCatalogue {
  id: string
  name: string
  events: EventSummary[]
}

export interface SportCatalogue {
  id: string
  code: string
  name: string
  competitions: CompetitionCatalogue[]
}

export function listSports(): Promise<SportCatalogue[]> {
  return apiFetch<SportCatalogue[]>('/v1/sportsbook/sports')
}

export interface Selection {
  id: string
  name: string
  odds_numerator: number
  odds_denominator: number
  status: string
}

export interface MarketDetail {
  id: string
  name: string
  status: string
  selections: Selection[]
}

export interface EventDetail {
  id: string
  name: string
  start_time: string
  status: string
  sport_code: string
  sport_name: string
  competition_name: string
  markets: MarketDetail[]
}

export function getEvent(id: string): Promise<EventDetail> {
  return apiFetch<EventDetail>(`/v1/sportsbook/events/${id}`)
}

// Mirrors internal/sportsbook/types.go's Rejection* constants.
export type RejectionCategory =
  | 'odds_changed'
  | 'event_not_open'
  | 'insufficient_funds'
  | 'rg_denied'
  | 'risk_denied'
  | 'jurisdiction_denied'
  | 'exposure_limit'

export interface Bet {
  id: string
  selection_id: string
  asset_code: string
  stake_amount: number
  odds_numerator: number
  odds_denominator: number
  potential_return: number
  status: string
  placed_at: string
}

/**
 * POST /v1/me/sportsbook/bets returns EITHER outcome as a 2xx - `accepted`
 * is the discriminator callers must branch on, never HTTP status alone
 * (201 vs 200), matching the server's own contract exactly
 * (placeBetResponse in sportsbook_handlers.go).
 */
export interface PlaceBetResponse {
  accepted: boolean
  bet?: Bet
  rejection_category?: RejectionCategory
  rejection_code?: string
  rejection_message?: string
}

export interface PlaceBetParams {
  selectionId: string
  stakeAmount: number
  assetCode: string
  expectedOddsNumerator: number
  expectedOddsDenominator: number
  /** Fresh per bet-slip submission - generated by the caller, never reused automatically on retry. */
  idempotencyKey: string
}

export function placeBet(params: PlaceBetParams): Promise<PlaceBetResponse> {
  return apiFetch<PlaceBetResponse>('/v1/me/sportsbook/bets', {
    method: 'POST',
    body: JSON.stringify({
      selection_id: params.selectionId,
      stake_amount: params.stakeAmount,
      asset_code: params.assetCode,
      expected_odds_numerator: params.expectedOddsNumerator,
      expected_odds_denominator: params.expectedOddsDenominator,
      idempotency_key: params.idempotencyKey,
    }),
  })
}

export function listMyBets(params: { limit?: number; offset?: number }): Promise<PagedResponse<Bet>> {
  return apiFetch<PagedResponse<Bet>>(`/v1/me/sportsbook/bets${buildQuery(params)}`)
}
