variable "name_prefix" {
  type = string
}

variable "private_subnet_ids" {
  type = list(string)
}

variable "security_group_id" {
  type = string
}

variable "instance_class" {
  description = "Staging-sized default. Bump for production (see runbook's promotion section)."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  type    = number
  default = 20
}

variable "engine_version" {
  description = "Postgres 16.x. Operator should confirm the latest supported 16.x minor at apply time via `aws rds describe-db-engine-versions --engine postgres`."
  type        = string
  default     = "16.4"
}

variable "master_username" {
  description = "RDS master user name. Named 'igaming' deliberately: an RDS master user already owns the initial database/schema it creates and holds the rds_superuser pseudo-role (CREATEROLE, no true SUPERUSER) — this IS the migration-owner role from docs/security/runtime-role-separation.md, not a separate bootstrap identity. cmd/migrate connects as this role."
  type        = string
  default     = "igaming"
}

variable "master_password" {
  description = "Generated by the secrets module (random_password), never typed here."
  type        = string
  sensitive   = true
}

variable "db_name" {
  type    = string
  default = "igaming_platform_staging"
}

variable "backup_retention_days" {
  description = "Automated backup retention. Short for staging (3-7 days recommended); production should use a longer window."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 1 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 1 and 35 (RDS limit)."
  }
}

variable "multi_az" {
  description = "Staging default false (single AZ, cost-optimized). Production must set true."
  type        = bool
  default     = false
}

variable "deletion_protection" {
  description = "Staging default false so the environment is fully disposable via terraform destroy. Production must set true."
  type        = bool
  default     = false
}

variable "kms_deletion_window_days" {
  type    = number
  default = 7
}

variable "tags" {
  type    = map(string)
  default = {}
}
